<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GeneticDiversity</AssemblyName>
    <RootNamespace>GeneticDiversity</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <RimWorldDir Condition="'$(RimWorldDir)' == ''">D:\steam\steamapps\common\RimWorld</RimWorldDir>
    <HarmonyPath Condition="'$(HarmonyPath)' == '' and Exists('$(RimWorldDir)\..\..\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll')">$(RimWorldDir)\..\..\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HarmonyPath>
    <HarmonyPath Condition="'$(HarmonyPath)' == '' and Exists('$(RimWorldDir)\Mods\Harmony\Current\Assemblies\0Harmony.dll')">$(RimWorldDir)\Mods\Harmony\Current\Assemblies\0Harmony.dll</HarmonyPath>
    <HarmonyPath Condition="'$(HarmonyPath)' == '' and Exists('D:\RimWorldModding\模组制作工作台\创意工坊其他模组及源码\HAR系列\已兼容\Humanoid Alien Races\1.6\Assemblies\0Harmony.dll')">D:\RimWorldModding\模组制作工作台\创意工坊其他模组及源码\HAR系列\已兼容\Humanoid Alien Races\1.6\Assemblies\0Harmony.dll</HarmonyPath>
    <OutputPath>$(MSBuildProjectDirectory)\..\..\1.6\Assemblies\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RimWorldDir)\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RimWorldDir)\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldDir)\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(HarmonyPath)</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>

